### ISSUE TITLE
GridBagLayout for UI

### ISSUE THREAD

**Issue by dgiri12** [SW-Dev-Methods-Team-2/Sharksoft#24]
Making UI design like floating grid design usually done by web designers for CSS. That same approach can be adopted for our project. https://docs.oracle.com/javase/tutorial/uiswing/layout/gridbag.html this link has a launch program button, and that program shows implementation as shown by oracle, it's pretty cool. Gridlayout doesn't work because it doesn't allow one component to occupy more than one row or column. BorderLayout doesn't work inside JPanel, and not using any layout at all and hard coding all the coordinates isn't an option either.

**Comment by sbowma15** [comment]
[3:47 PM] Bowman, Shane
    so youre talking about using gridbaglayout to look like floating grid design for webpages?
​[3:48 PM] Bowman, Shane
    if so, I believe I can do about the same with java swing
​[3:49 PM] Bowman, Shane
    I was hoping to just get everything connected to the buttons etc then we can change out the buttons and layout 
​[3:49 PM] Bowman, Shane
    im gonna look more into it and play with it
​[3:57 PM] Bowman, Shane
    I have text fields and stuff on the current gui skeleton now, but I think im gonna do the close out button method to clear the sim first so we at least have it working and I think if we use another library we can still use the method

**Comment by sbowma15** [comment]
so youre talking about using gridbaglayout to look like floating grid design for webpages?
    if so, I believe I can do about the same with java swing
​I was hoping to just get everything connected to the buttons etc then we can change out the buttons and layout 
    im gonna look more into it and play with it
    I have text fields and stuff on the current gui skeleton now, but I think im gonna do the close out button method to clear the sim first so we at least have it working and I think if we use another library we can still use the method

**Comment by sbowma15** [comment]
Gridbaglayout can for sure be worth nit, Ive just got to familiarize myself with it as im more experienced with swing

**Comment by sbowma15** [comment]
Ill be back on it in an hour or so from now

**Comment by dgiri12** [comment]
> Gridbaglayout can for sure be worth it, Ive just got to familiarize myself with it as im more experienced with swing

yeah totally, gridbaglayout is part of swing after all

**Comment by sbowma15** [comment]
> > Gridbaglayout can for sure be worth it, Ive just got to familiarize myself with it as im more experienced with swing
> 
> yeah totally, gridbaglayout is part of swing after all

oh yea derrrp. hahaha

**Comment by sbowma15** [comment]
> > > Gridbaglayout can for sure be worth it, Ive just got to familiarize myself with it as im more experienced with swing
> > 
> > 
> > yeah totally, gridbaglayout is part of swing after all
> 
> oh yea derrrp. hahaha

Yea i just havnt really played with gridbag. I should have it working well tonight

**Comment by dgiri12** [comment]
here it is man, the tabs UI we were trying to make, now we can get rid of those jframes, and have everything live in jpanels. When Gui components are grouped inside jpanels, like one panel for crud and one panel for sim, and so forth, we can set one visibility value to control the visibility of the entire panel.

[code.docx](https://github.com/SW-Dev-Methods-Team-2/Sharksoft/files/5426630/code.docx)

**Comment by sbowma15** [comment]
Thats actually what it's doing right now, so it shouldn't be hard to switch up the layout and use the same visibility toggles

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dgiri12** [comment]
This has been completed by the help of Netbeans swing editor
