### ISSUE TITLE
website - order can be cancelled

### ISSUE THREAD

**Issue by Lfickling** [SW-Dev-Methods-Team-2/Sharksoft#31]
-delete order from sales orders db?
or: add new column 'cancelled' 

- when you cancel the order stays in sales orders but is marked cancelled so it can still be seen in historical orders
- items are re-added to inventory.

**Comment by Lfickling** [comment]
cancellation should only be allowed for a certain period of time (1 day?) based on order time stamp

**Comment by Lfickling** [comment]
3 days per derek

**Comment by jgonzo3224** [comment]
Orders can be deleted/cancelled now.
